using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Moralis.AuthApi.Models
{
    /// <summary>
    /// Respopnse returned by the Challenge operation.
    /// </summary>
    public class ChallengeResponseDto
    {
        /// <summary>
        /// Internal identifier
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Message meant to be signed.
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// Profile Id generated by the Moralis Authentication API.
        /// </summary>
        [DataMember(Name = "profileId", EmitDefaultValue = false)]
        [JsonProperty(PropertyName = "profileId")]
        public string ProfileId { get; set; }
    }
}
